# Generated by Django 4.0.6 on 2022-07-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contenttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
